spring.application.name=ecommerce-parquesoft
server.port=${PORT:8080}

# Configuración de Base de Datos (Adaptable para Local y Producción)
# Si existen variables de entorno (Render/Railway), las usa. Si no, usa H2 localmente.
spring.datasource.url=${DB_URL:jdbc:h2:mem:testdb}
spring.datasource.username=${DB_USER:sa}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.defer-datasource-initialization=true